apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: petclinic-cluster
  region: us-east-1
availabilityZones: ["us-east-1a", "us-east-1f", "us-east-1c"]
managedNodeGroups:
  - name: dmr-ng-1
    instanceType: t3a.medium
    desiredCapacity: 1
    minSize: 1
    maxSize: 2
    volumeSize: 8
  - name: dmr-ng-2
    instanceType: t2.micro
    desiredCapacity: 2
    minSize: 2
    maxSize: 3
    volumeSize: 8